### ISSUE TITLE
Update tests to use postgres

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-workflows#119]
Developing/testing with sqlite but deploying on postgres is causing issues. Migrations don't work the same way, and assumptions about PK sequences and exception types don't hold across both databases.

Since we ultimately need to rely on postgres behaviors in the deployment, we should be running automated tests with postgres to avoid surprises.

**Comment by dleehr** [comment]
<details>
<summary>Tests that are failing under postgres as of c7d52de9ade2a14499607fd2d86e090e96871eb8</summary>

```
$ python manage.py test
Creating test database for alias 'default'...
................WARNING:django.request:Not Found: /api/dds-projects/abc123/
...WARNING:django.request:Not Found: /api/dds-resources/
.......F..........ERROR:django.request:Internal Server Error: /api/job-answer-sets/1/create-job/
Traceback (most recent call last):
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/rest_framework/views.py", line 474, in dispatch
    response = self.handle_exception(exc)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/rest_framework/views.py", line 434, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/rest_framework/views.py", line 471, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/Users/dcl9/Code/python/bespin-api/data/api.py", line 307, in create_job
    job = job_factory.create_job()
  File "/Users/dcl9/Code/python/bespin-api/data/jobfactory.py", line 112, in create_job
    JobDDSOutputProject.objects.create(job=job, dds_user_credentials=worker_user_credentials)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
ValueError: oops
..................................F........WARNING:django.request:Not Found: /api/users/current-user//109
.......................................................F....F.......................................F.
======================================================================
FAIL: testUserOnlySeeAllCredsButNoTokens (data.tests_api.DDSUserCredentialTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dcl9/Code/python/bespin-api/data/tests_api.py", line 235, in testUserOnlySeeAllCredsButNoTokens
    self.assertEqual({'id': 1, 'user': 2, 'endpoint': 1}, response.data[0])
AssertionError: {'endpoint': 1, 'id': 1, 'user': 2} != OrderedDict([('id', 7), ('user', 32), ('endpoint', 6)])

======================================================================
FAIL: test_job_restart (data.tests_api.JobsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/Users/dcl9/Code/python/bespin-api/data/tests_api.py", line 693, in test_job_restart
    mock_make_client().restart_job.assert_called_with(str(1))
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Expected call: restart_job('1')
Actual call: restart_job(u'47')

======================================================================
FAIL: test_jobs_cant_share_job_tokens (data.tests_models.JobTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dcl9/Code/python/bespin-api/data/tests_models.py", line 321, in test_jobs_cant_share_job_tokens
    self.assertTrue(str(raised_error.exception).startswith('UNIQUE constraint failed'))
AssertionError: False is not true

======================================================================
FAIL: test_token_must_be_unique (data.tests_models.JobTokenTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dcl9/Code/python/bespin-api/data/tests_models.py", line 601, in test_token_must_be_unique
    self.assertTrue(str(raised_error.exception).startswith('UNIQUE constraint failed'))
AssertionError: False is not true

======================================================================
FAIL: test_start_job (data.test_lando.LandoJobTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/Users/dcl9/Code/python/bespin-api/data/test_lando.py", line 65, in test_start_job
    call(self.user, '1235', '5432')
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/mock/mock.py", line 969, in assert_has_calls
    ), cause)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Calls not found.
Expected: [call(<User: test_user>, '1234', '5432'),
 call(<User: test_user>, '1235', '5432')]
Actual: [call(<User: test_user>, u'1235', u'5432'),
 call(<User: test_user>, u'1234', u'5432')]

----------------------------------------------------------------------
Ran 182 tests in 40.992s

FAILED (failures=5)
Destroying test database for alias 'default'...
```

</details>
