### ISSUE TITLE
Loading workflows fails with schema-salad==2.6.20171201034858

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-workflows#128]
Upon trying to load a workflow on dev, it fails with:

```
[Wed Feb 14 20:24:36.222922 2018] [wsgi:error] [pid 22:tid 139629453899520] ERROR:data.importers:Unable to import workflow
[Wed Feb 14 20:24:36.223218 2018] [wsgi:error] [pid 22:tid 139629453899520] Traceback (most recent call last):
[Wed Feb 14 20:24:36.223273 2018] [wsgi:error] [pid 22:tid 139629453899520]   File "/app/data/importers.py", line 298, in _load
[Wed Feb 14 20:24:36.223292 2018] [wsgi:error] [pid 22:tid 139629453899520]     wf_importer.run()
[Wed Feb 14 20:24:36.223312 2018] [wsgi:error] [pid 22:tid 139629453899520]   File "/app/data/importers.py", line 254, in run
[Wed Feb 14 20:24:36.223325 2018] [wsgi:error] [pid 22:tid 139629453899520]     self._create_models()
[Wed Feb 14 20:24:36.223355 2018] [wsgi:error] [pid 22:tid 139629453899520]   File "/app/data/importers.py", line 226, in _create_models
[Wed Feb 14 20:24:36.223370 2018] [wsgi:error] [pid 22:tid 139629453899520]     workflow_name = self.cwl_document.get('label')
[Wed Feb 14 20:24:36.223382 2018] [wsgi:error] [pid 22:tid 139629453899520]   File "/app/data/importers.py", line 77, in get
[Wed Feb 14 20:24:36.223412 2018] [wsgi:error] [pid 22:tid 139629453899520]     return self.parsed.tool.get(key)
[Wed Feb 14 20:24:36.223445 2018] [wsgi:error] [pid 22:tid 139629453899520]   File "/app/data/importers.py", line 60, in parsed
[Wed Feb 14 20:24:36.223458 2018] [wsgi:error] [pid 22:tid 139629453899520]     self._parsed = load_tool(self.url + '#main', defaultMakeTool)
[Wed Feb 14 20:24:36.223470 2018] [wsgi:error] [pid 22:tid 139629453899520]   File "/usr/local/lib/python2.7/site-packages/cwltool/load_tool.py", line 266, in load_tool
[Wed Feb 14 20:24:36.223482 2018] [wsgi:error] [pid 22:tid 139629453899520]     fetcher_constructor=fetcher_constructor)
[Wed Feb 14 20:24:36.223494 2018] [wsgi:error] [pid 22:tid 139629453899520]   File "/usr/local/lib/python2.7/site-packages/cwltool/load_tool.py", line 57, in fetch_document
[Wed Feb 14 20:24:36.223523 2018] [wsgi:error] [pid 22:tid 139629453899520]     workflowobj = document_loader.fetch(fileuri)
[Wed Feb 14 20:24:36.223551 2018] [wsgi:error] [pid 22:tid 139629453899520]   File "/usr/local/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 914, in fetch
[Wed Feb 14 20:24:36.223566 2018] [wsgi:error] [pid 22:tid 139629453899520]     text = self.fetch_text(url)
[Wed Feb 14 20:24:36.223594 2018] [wsgi:error] [pid 22:tid 139629453899520]   File "/usr/local/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 144, in fetch_text
[Wed Feb 14 20:24:36.223611 2018] [wsgi:error] [pid 22:tid 139629453899520]     raise RuntimeError(url, e)
[Wed Feb 14 20:24:36.223623 2018] [wsgi:error] [pid 22:tid 139629453899520] RuntimeError: (u'https://github.com/Duke-GCB/bespin-cwl/releases/download/v0.9.0/exomeseq.cwl', TypeError('an integer is required',))
10.14.46.3 - - [14/Feb/2018:20:24:35 +0000] "POST /api/admin/import-workflow-questionnaire/ HTTP/1.1" 400 38
```

The version of schema salad is schema-salad==2.6.20171201034858, and that fails.

On my local installation, I have `schema-salad==2.5.20170428142041`, and it runs successfully.

**Comment by dleehr** [comment]
This is only happening inside docker. I was able to disable some exception gobbling to get to the real root of the problem (and why the error is "an integer is required". The CacheControl package that schema salad uses with requests is failing:

```
 Importing Workflow version 4
 Unable to import workflow
 Traceback (most recent call last):
   File "/app/data/importers.py", line 298, in _load
     wf_importer.run()
   File "/app/data/importers.py", line 254, in run
     self._create_models()
   File "/app/data/importers.py", line 226, in _create_models
     workflow_name = self.cwl_document.get('label')
   File "/app/data/importers.py", line 77, in get
     return self.parsed.tool.get(key)
   File "/app/data/importers.py", line 60, in parsed
     self._parsed = load_tool(self.url + '#main', defaultMakeTool)
   File "/usr/local/lib/python2.7/site-packages/cwltool/load_tool.py", line 345, in load_tool
     fetcher_constructor=fetcher_constructor)
   File "/usr/local/lib/python2.7/site-packages/cwltool/load_tool.py", line 111, in fetch_document
     workflowobj = document_loader.fetch(fileuri)
   File "/usr/local/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 908, in fetch
     text = self.fetch_text(url)
   File "/usr/local/lib/python2.7/site-packages/schema_salad/ref_resolver.py", line 140, in fetch_text
     resp = self.session.get(url)
   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in get
     return self.request('GET', url, **kwargs)
   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
     resp = self.send(prep, **send_kwargs)
   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 617, in send
     history = [resp for resp in gen] if allow_redirects else []
   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 177, in resolve_redirects
     **adapter_kwargs
   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 628, in send
     r.content
   File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 755, in content
     self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
   File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 676, in generate
     for chunk in self.raw.stream(chunk_size, decode_content=True):
   File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 357, in stream
     data = self.read(amt=amt, decode_content=decode_content)
   File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 314, in read
     data = self._fp.read(amt)
   File "/usr/local/lib/python2.7/site-packages/cachecontrol/filewrapper.py", line 63, in read
     self._close()
   File "/usr/local/lib/python2.7/site-packages/cachecontrol/filewrapper.py", line 50, in _close
     self.__callback(self.__buf.getvalue())
   File "/usr/local/lib/python2.7/site-packages/cachecontrol/controller.py", line 275, in cache_response
     self.serializer.dumps(request, response, body=body),
   File "/usr/local/lib/python2.7/site-packages/cachecontrol/caches/file_cache.py", line 101, in set
     with _secure_open_write(lock.path, self.filemode) as fh:
   File "/usr/local/lib/python2.7/site-packages/cachecontrol/caches/file_cache.py", line 42, in _secure_open_write
     fd = os.open(filename, flags, fmode)
 TypeError: an integer is required
```

**Comment by dleehr** [comment]
Underlying issue is a bug in [schema_salad](https://github.com/common-workflow-language/schema_salad/issues/158), but should be able to workaround by setting `TMP` as an environment variable.
