### ISSUE TITLE
tests failing due to cannot import name 'autotranslate'

### ISSUE THREAD

**Issue by johnbradley** [Duke-GCB/bespin-workflows#222]
```
ImportError: Failed to import test module: data.tests_importers
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/circleci/project/data/tests_importers.py", line 2, in <module>
    from data.importers import CWLDocument, MethodsDocumentContents, SCHEMA_ORG_CITATION, \
  File "/home/circleci/project/data/importers.py", line 3, in <module>
    from cwltool.context import LoadingContext
  File "/home/circleci/project/venv/lib/python3.6/site-packages/cwltool/context.py", line 7, in <module>
    from schema_salad import schema
  File "/home/circleci/project/venv/lib/python3.6/site-packages/schema_salad/__init__.py", line 35, in <module>
    from past import autotranslate  # type: ignore
ImportError: cannot import name 'autotranslate'
```

https://circleci.com/gh/Duke-GCB/bespin-api/612

**Comment by johnbradley** [comment]
Looks like this was a breaking change in future 0.18.x: https://github.com/PythonCharmers/python-future/pull/487

**Comment by johnbradley** [comment]
This failing import has been removed from schema salad: https://github.com/common-workflow-language/schema_salad/pull/211
