### ISSUE TITLE
Migration fails due to null share_group_id values

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-workflows#59]
Upon trying to redeploy bespin-web, the server process starts but attempts to list jobs result in a 500 error due to a failed migration

```
ProgrammingError: column data_job.vm_volume_name does not exist
LINE 1: ..._job"."vm_flavor", "data_job"."vm_instance_name", "data_job"...
```

The migration to add the share_group is failing:

```
Postgres is up - executing command
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, data, gcb_web_auth, sessions
Running migrations:
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 204, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 495, in alter_field
    old_db_params, new_db_params, strict)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/postgresql/schema.py", line 117, in _alter_field
    new_db_params, strict,
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 649, in _alter_field
    params,
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 112, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: column "share_group_id" contains null values
```

**Comment by johnbradley** [comment]
Can we just clear out the existing data?

**Comment by dleehr** [comment]
Yeah I can do that.

**Comment by dleehr** [comment]
This has been more trouble than I thought. This migration that fails is trying to add the share group id field to the job_questionnaire. It's possible that we'll have workflow outputs that we don't need to share with a reviewer, so I don't think we should require this at the schema level right now.

**Comment by dleehr** [comment]
I created a share group and got the migrations to complete

**Comment by johnbradley** [comment]
With the current changes if you don't share the job results with someone the data will just sit in the service account's DukeDS storage.

**Comment by dleehr** [comment]
On a fresh database, the `loadworkflow` command now fails. It creates a JobQuestionnaire without a share group id:

```
$ python manage.py loadworkflow https://raw.githubusercontent.com/Duke-GCB/bespin-cwl/exome-seq/packed-workflows/exomeseq-packed.cwl 1 "Exome Seq" "Long description" ~/Code/yaml/bespin-cwl/examples/exome-seq/exomeseq.json m1.large gcb_dev
No handlers could be found for logger "cwltool"
Workflow 'Whole Exome Sequencing' created with id 1
Workflow Version 'Whole Exome Sequence analysis using GATK best practices - Germline SNP & Indel Discovery
' created with id 1
VMFlavor 'm1.large' created with id 1
VMProject 'gcb_dev' created with id 1
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/dcl9/Code/python/bespin-api/data/management/commands/loadworkflow.py", line 211, in handle
    jq_importer.run()
  File "/Users/dcl9/Code/python/bespin-api/data/management/commands/loadworkflow.py", line 125, in run
    self._create_models()
  File "/Users/dcl9/Code/python/bespin-api/data/management/commands/loadworkflow.py", line 120, in _create_models
    vm_project=self.vm_project,
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/db/models/query.py", line 475, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/db/models/query.py", line 513, in _create_object_from_params
    six.reraise(*exc_info)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/db/models/query.py", line 505, in _create_object_from_params
    obj = self.create(**params)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/db/models/query.py", line 399, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/dcl9/Code/python/bespin-api/env/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: data_jobquestionnaire.share_group_id
```

The obvious way forward is to specify the share group in the load workflow command. We'd also need a command that creates share groups with users and their DDS IDs.

That would be fine, but I'm not convinced that every workflow and every job needs a share group, so I'm hesitant to make a lot of changes to fix this. Should get feedback next week.
