### ISSUE TITLE
Failed job couldn't create job-error due to MemoryError

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-workflows#61]
```
10.16.72.81 - - [10/Aug/2017:04:27:55 +0000] "PUT /api/admin/jobs/29/ HTTP/1.1" 200 5685
10.16.72.81 - - [10/Aug/2017:04:27:55 +0000] "GET /api/admin/jobs/29/ HTTP/1.1" 200 5685
10.16.72.81 - - [10/Aug/2017:04:27:55 +0000] "GET /api/admin/jobs/29/ HTTP/1.1" 200 5685
[Thu Aug 10 04:28:06.891596 2017] [wsgi:error] [pid 31:tid 139811050452736] ERROR:django.request:Internal Server Error: /api/admin/job-errors/
[Thu Aug 10 04:28:06.892104 2017] [wsgi:error] [pid 31:tid 139811050452736] Traceback (most recent call last):
[Thu Aug 10 04:28:06.892135 2017] [wsgi:error] [pid 31:tid 139811050452736]   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
[Thu Aug 10 04:28:06.892160 2017] [wsgi:error] [pid 31:tid 139811050452736]     response = get_response(request)
[Thu Aug 10 04:28:06.892182 2017] [wsgi:error] [pid 31:tid 139811050452736]   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
[Thu Aug 10 04:28:06.892192 2017] [wsgi:error] [pid 31:tid 139811050452736]     response = self.process_exception_by_middleware(e, request)
[Thu Aug 10 04:28:06.892201 2017] [wsgi:error] [pid 31:tid 139811050452736]   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
[Thu Aug 10 04:28:06.892217 2017] [wsgi:error] [pid 31:tid 139811050452736]     response = response.render()
[Thu Aug 10 04:28:06.892239 2017] [wsgi:error] [pid 31:tid 139811050452736]   File "/usr/local/lib/python2.7/site-packages/django/template/response.py", line 109, in render
[Thu Aug 10 04:28:06.892250 2017] [wsgi:error] [pid 31:tid 139811050452736]     self.content = self.rendered_content
[Thu Aug 10 04:28:06.892259 2017] [wsgi:error] [pid 31:tid 139811050452736]   File "/usr/local/lib/python2.7/site-packages/rest_framework/response.py", line 72, in rendered_content
[Thu Aug 10 04:28:06.892268 2017] [wsgi:error] [pid 31:tid 139811050452736]     ret = renderer.render(self.data, accepted_media_type, context)
[Thu Aug 10 04:28:06.892276 2017] [wsgi:error] [pid 31:tid 139811050452736]   File "/usr/local/lib/python2.7/site-packages/rest_framework/renderers.py", line 103, in render
[Thu Aug 10 04:28:06.892285 2017] [wsgi:error] [pid 31:tid 139811050452736]     separators=separators
[Thu Aug 10 04:28:06.892300 2017] [wsgi:error] [pid 31:tid 139811050452736]   File "/usr/local/lib/python2.7/json/__init__.py", line 251, in dumps
[Thu Aug 10 04:28:06.892321 2017] [wsgi:error] [pid 31:tid 139811050452736]     sort_keys=sort_keys, **kw).encode(obj)
[Thu Aug 10 04:28:06.892331 2017] [wsgi:error] [pid 31:tid 139811050452736]   File "/usr/local/lib/python2.7/json/encoder.py", line 207, in encode
[Thu Aug 10 04:28:06.892339 2017] [wsgi:error] [pid 31:tid 139811050452736]     chunks = self.iterencode(o, _one_shot=True)
[Thu Aug 10 04:28:06.892348 2017] [wsgi:error] [pid 31:tid 139811050452736]   File "/usr/local/lib/python2.7/json/encoder.py", line 270, in iterencode
[Thu Aug 10 04:28:06.892356 2017] [wsgi:error] [pid 31:tid 139811050452736]     return _iterencode(o, 0)
[Thu Aug 10 04:28:06.892365 2017] [wsgi:error] [pid 31:tid 139811050452736]   File "/usr/local/lib/python2.7/json/encoder.py", line 39, in encode_basestring
[Thu Aug 10 04:28:06.892373 2017] [wsgi:error] [pid 31:tid 139811050452736]     return '"' + ESCAPE.sub(replace, s) + '"'
[Thu Aug 10 04:28:06.892382 2017] [wsgi:error] [pid 31:tid 139811050452736] MemoryError
```

**Comment by dleehr** [comment]
Job 49 had a similar issue. The console output of toil is uploaded to the job-error and it's too big for the UI to render or the API to display.

While this is probably more common in workflows under development, it's still likely that user workflows will fail, and that shouldn't break the web application. So I think this needs to be addressed before the beta release.

We discussed some approaches to limiting what gets uploaded into the job-error but I don't have an issue that documents this.

Some additional discussion in https://github.com/Duke-GCB/lando/issues/46, but I think the overall strategy should be 

1. Limit the size of a job-error's contents in bespin-api (this prevents the UI and API from breaking)
2. Lando should be aware of this limit and either truncate logs it would upload or be more selective about what it reports in the error. Perhaps when there's an error at the workflow level (as opposed to staging data), that can be summarized
3. For such failures, we will not delete the VM. The only practical way I can debug these issues anyways is to log into the VM and view the logs from there.

**Comment by dleehr** [comment]
Number of workflow stderr lines uploaded is limited by lando in https://github.com/Duke-GCB/lando/pull/86, so that should address this issue. VMs for failed jobs are not deleted.
